services:
  api-pg:
    image: bitnami/postgresql
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api-pg
  
  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686" # UI
      - "6831:6831/udp" # Traces UDP
      - "14268:14268" # Traces HTTP
      - "4317:4317" # OTLP/gRPC
      - "4318:4318" # OTLP/HTTP